name: Deploy Static App to GitHub Pages

on:
  push:
    branches:
      - main  # o la rama que uses para despliegue

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Crear el archivo config.js con el secreto API_KEY
      - name: Create config.js with secret API_KEY
        run: |
          echo "const CONFIG = { API_KEY: '${{ secrets.API_KEY }}' };" > config/config.js

      # Añadir config.js al .gitignore para evitar que se suba a GitHub
      - name: Add config.js to .gitignore
        run: |
          echo "config/config.js" >> .gitignore

      # Desplegar el sitio a GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # La rama en la que se desplegará el sitio
          folder: .         # El directorio a desplegar (en este caso, la raíz del proyecto)
